
+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/tech_cells_generic-6e6736c6cf5dbb6b/src/rtl/tc_sram.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/tech_cells_generic-6e6736c6cf5dbb6b/src/rtl/tc_sram_impl.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/tech_cells_generic-6e6736c6cf5dbb6b/src/rtl/tc_clk.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/tech_cells_generic-6e6736c6cf5dbb6b/src/deprecated/pulp_clock_gating_async.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/tech_cells_generic-6e6736c6cf5dbb6b/src/deprecated/cluster_clk_cells.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/tech_cells_generic-6e6736c6cf5dbb6b/src/deprecated/pulp_clk_cells.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/binary_to_gray.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cb_filter_pkg.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cc_onehot.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_reset_ctrlr_pkg.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cf_math_pkg.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/clk_int_div.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/delta_counter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/ecc_pkg.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/edge_propagator_tx.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/exp_backoff.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/fifo_v3.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/gray_to_binary.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/isochronous_4phase_handshake.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/isochronous_spill_register.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/lfsr.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/lfsr_16bit.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/lfsr_8bit.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/lossy_valid_to_stream.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/mv_filter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/onehot_to_bin.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/plru_tree.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/popcount.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/rr_arb_tree.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/rstgen_bypass.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/serial_deglitch.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/shift_reg.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/shift_reg_gated.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/spill_register_flushable.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_demux.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_filter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_fork.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_intf.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_join_dynamic.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_mux.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_throttle.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/sub_per_hash.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/sync.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/sync_wedge.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/unread.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/read.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/addr_decode_dync.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_2phase.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_4phase.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/clk_int_div_static.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/addr_decode.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/addr_decode_napot.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/multiaddr_decode.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cb_filter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_fifo_2phase.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/clk_mux_glitch_free.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/counter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/ecc_decode.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/ecc_encode.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/edge_detect.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/lzc.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/max_counter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/rstgen.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/spill_register.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_delay.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_fifo.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_fork_dynamic.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_join.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_reset_ctrlr.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_fifo_gray.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/fall_through_register.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/id_queue.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_to_mem.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_arbiter_flushable.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_fifo_optimal_wrap.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_register.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_xbar.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_fifo_gray_clearable.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/cdc_2phase_clearable.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/mem_to_banks_detailed.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_arbiter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/stream_omega_net.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/mem_to_banks.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/test/cdc_2phase_synth.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/test/id_queue_synth.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/test/stream_arbiter_synth.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/test/ecc_synth.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/test/synth_bench.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/clock_divider_counter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/clk_div.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/find_first_one.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/generic_LFSR_8bit.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/generic_fifo.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/prioarbiter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/pulp_sync.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/pulp_sync_wedge.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/rrarbiter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/clock_divider.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/fifo_v2.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/deprecated/fifo_v1.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/edge_propagator_ack.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/edge_propagator.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/src/edge_propagator_rx.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_pkg.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_intf.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_atop_filter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_burst_splitter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_bus_compare.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_cdc_dst.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_cdc_src.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_cut.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_delayer.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_demux_simple.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_dw_downsizer.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_dw_upsizer.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_fifo.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_id_remap.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_id_prepend.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_isolate.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_join.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_demux.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_dw_converter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_from_mem.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_join.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_lfsr.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_mailbox.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_mux.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_regs.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_to_apb.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_to_axi.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_modify_address.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_mux.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_rw_join.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_rw_split.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_serializer.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_slave_compare.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_throttle.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_to_detailed_mem.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_cdc.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_demux.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_err_slv.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_dw_converter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_from_mem.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_id_serialize.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lfsr.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_multicut.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_to_axi_lite.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_to_mem.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_iw_converter.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_lite_xbar.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_xbar.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_to_mem_banked.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_to_mem_interleaved.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_to_mem_split.sv
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/src/axi_xp.sv

+define+TARGET_SYNTHESIS
+define+TARGET_SYNTH_TEST
+define+TARGET_VERILATOR
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/.bender/git/checkouts/common_cells-3e2fcccecd7aee7b/include
+incdir+/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/include
/home/matt/Documents/Personal/PersonalProjects/Cocotb/axiToApb/axi/test/axi_synth_bench.sv

